// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qncufdtigxltdeaasynw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuY3VmZHRpZ3hsdGRlYWFzeW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTQ2NzAsImV4cCI6MjA3MTI3MDY3MH0.k_DVoQfSd45GaCkpVeAob62FFmHmzKpfsvplxJJY_-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});